name: Build wheels

on: [ push ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-10.15]

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Used to host cibuildwheel
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.11.0
      
      - name: Use the new setup
        run: |
          mv setup.py libxc/

      - name: Build wheels
        run: |
          cd libxc
          python -m cibuildwheel --output-dir ../wheelhouse
          cd ..
        env:
          CIBW_BUILD: cp37-*_x86_64  # cp3*-*
          CIBW_BEFORE_BUILD: |
            python -m pip install cmake
            python -m pip install py-cpuinfo
            python -m cpuinfo
            cmake --version
          CIBW_BEFORE_TEST: python -m pip install pytest
          CIBW_TEST_COMMAND: ls -lh  # pytest ~/libxc/testsuite/pytest/

      - uses: actions/upload-artifact@v2
        with:
          name: python-wheels
          path: ./wheelhouse/*.whl
  
  publish_testpypi:
    name: Publish to TestPyPI
    needs: [build_wheels]
    runs-on: [ubuntu-latest]

    steps:
      - name: Download Python wheels
        uses: actions/download-artifact@v2
        with:
          name: python-wheels
          path: dist/

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Publish distribution to Test PyPI
        if: ${{ !(startsWith(github.ref, 'refs/tags')) }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
  
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
